version: "3"

services:
  web:
    image: karbka/rest_flask_2:latest
    build:
      context: ./web
    restart: always
    ports:
      - "5000:5000"
    links:
      - db

  db:
    image: karbka/rest_flask_2:latest
      build:
        context: ./db