version: "3"

services:
  base:
    image: base:latest
    build:
      context: base

  web_operation:
    build:
      context: web_operation
    restart: always
    ports:
      - "5000:5000"
    depends_on:
      - base

  web_store:
    build:
      context: web_store
    restart: always
    ports:
      - "5001:5000"
    depends_on:
      - base

  web_text_similarity:
    build:
      context: web_text_similarity
    restart: always
    ports:
      - "5002:5000"
    depends_on:
      - base

  web_image_classification:
    build:
      context: web_image_classification
    restart: always
    ports:
      - "5003:5000"
    depends_on:
      - base

  db:
    build:
      context: ./db
    ports:
      - "27017:27017"